### ISSUE TITLE
[FF]Deleted from add-on store?

### ISSUE THREAD

**Issue by tyrope** [bgotink/IngressIdentity#39]
either the website links incorrectly, or mozilla deleted your software from the site.
[the link on your homepage](https://addons.mozilla.org/en-US/firefox/addon/ingressidentity/) results in a 404 (effectively) and [searching for "Ingress Identity"](https://addons.mozilla.org/en-US/firefox/search/?q=Ingress+Identity&appver=&platform=) yields no (useful) results.

**Comment by bgotink** [comment]
I've tried a number of times to get this extension to pass review, but I've run out of patience. If anyone wants to pick this up, feel free. Until then I'm afraid FF users won't be able to use the AMO store.
