### ISSUE TITLE
where is the data for the badge icons being pulled from?

### ISSUE THREAD

**Issue by vally78** [bgotink/IngressIdentity#43]
I am trying to create my spreadsheet to resemble your sample, without all the extras and wanted to know which pages were required for the badge icons to show up on user pages.

**Comment by bgotink** [comment]
You don't need any of the extras for the extra profile item to appear. This extra item will only show on the about tab of the player's profile page.

For example:
![image](https://cloud.githubusercontent.com/assets/821510/7055657/747f5296-de45-11e4-958e-d71d3c6ddd55.png)
will result in
![image](https://cloud.githubusercontent.com/assets/821510/7055654/6b057efc-de45-11e4-9466-47540198c63a.png)
![image](https://cloud.githubusercontent.com/assets/821510/7055664/8859344e-de45-11e4-8261-d6ea982649c2.png)

I'd personally enable the "profile pop-up", as those pop-ups aren't shown on pages unless you hover over a name. That way the extension doesn't mess with your regular Google+ user experience, but you still have all the information readily available by hovering over a player's name.

**Comment by bgotink** [comment]
Hi @vally78,

I think I misinterpreted your question here :facepalm:.
Was the answer I gave on the Chrome WebStore support sufficiently clear for you?

**Comment by vally78** [comment]
when i look at my husbands profile, it does not show any of the anomalies he has been in.  What spreadsheet do i enter those into.Your work is great, btw.  It is nicely designed for ease of use, and very aesthetically pleasing.  My  profile:  https://plus.google.com/u/0/115469837571155605706  


Under anomaly, i show that it "SAYS" helios, from where i entered it in the spreadsheet, but which sheet do i have to enter it to make the actual badge icon appear, like under your profile.

PS, if you would like, my gmail address is valerielboss@gmail.com  
(the only thing i use my yahoo account for these days is signing up for junk) Valerie BossDixon, IL 61021
815-556-9273

 


     On Wednesday, April 8, 2015 4:21 PM, Bram Gotink <notifications@github.com> wrote:
   

 You don't need any of the extras for the extra profile item to appear. This extra item will only show on the about tab of the player's profile page.For example:

will result in

I'd personally enable the "profile pop-up", as those pop-ups aren't shown on pages unless you hover over a name. That way the extension doesn't mess with your regular Google+ user experience, but you still have all the information readily available by hovering over a player's name.—

**Comment by vally78** [comment]
aha, so new spreadsheet for each anomaly, got it.  Do i have to call the sheet anything special?  i guess i am just as intrigued by the process of all this working, as much as the end results.



 Valerie BossDixon, IL 61021
815-556-9273

 


     On Thursday, April 9, 2015 4:16 PM, Valerie Boss <vally78@yahoo.com> wrote:
   

 when i look at my husbands profile, it does not show any of the anomalies he has been in.  What spreadsheet do i enter those into.Your work is great, btw.  It is nicely designed for ease of use, and very aesthetically pleasing.  My  profile:  https://plus.google.com/u/0/115469837571155605706  


Under anomaly, i show that it "SAYS" helios, from where i entered it in the spreadsheet, but which sheet do i have to enter it to make the actual badge icon appear, like under your profile.

PS, if you would like, my gmail address is valerielboss@gmail.com  
(the only thing i use my yahoo account for these days is signing up for junk) Valerie BossDixon, IL 61021
815-556-9273

 


     On Wednesday, April 8, 2015 4:21 PM, Bram Gotink <notifications@github.com> wrote:
   

 You don't need any of the extras for the extra profile item to appear. This extra item will only show on the about tab of the player's profile page.For example:

will result in

I'd personally enable the "profile pop-up", as those pop-ups aren't shown on pages unless you hover over a name. That way the extension doesn't mess with your regular Google+ user experience, but you still have all the information readily available by hovering over a player's name.—

**Comment by vally78** [comment]
aha!  i just found the actual files behind the project, and your readmes on github.  dont know why i didnt look sooner.  I can figure it out from here.  But again, really stellar work!  I added you on G+, hope you dont mind.



 Valerie BossDixon, IL 61021
815-556-9273

 


     On Thursday, April 9, 2015 4:16 PM, Valerie Boss <vally78@yahoo.com> wrote:
   

 when i look at my husbands profile, it does not show any of the anomalies he has been in.  What spreadsheet do i enter those into.Your work is great, btw.  It is nicely designed for ease of use, and very aesthetically pleasing.  My  profile:  https://plus.google.com/u/0/115469837571155605706  


Under anomaly, i show that it "SAYS" helios, from where i entered it in the spreadsheet, but which sheet do i have to enter it to make the actual badge icon appear, like under your profile.

PS, if you would like, my gmail address is valerielboss@gmail.com  
(the only thing i use my yahoo account for these days is signing up for junk) Valerie BossDixon, IL 61021
815-556-9273

 


     On Wednesday, April 8, 2015 4:21 PM, Bram Gotink <notifications@github.com> wrote:
   

 You don't need any of the extras for the extra profile item to appear. This extra item will only show on the about tab of the player's profile page.For example:

will result in

I'd personally enable the "profile pop-up", as those pop-ups aren't shown on pages unless you hover over a name. That way the extension doesn't mess with your regular Google+ user experience, but you still have all the information readily available by hovering over a player's name.—

**Comment by vally78** [comment]
Yes, the chrome store answer helped.  I now understand that the "anomaly" column on the metadata sheet within the whole spreadsheet is what controls the anomaly badge icons.  Also, now i see that there needs to be a separate sheet within the spreadsheet for each unique anomaly badge icon.  Than you.

**Comment by bgotink** [comment]
You're welcome! If you have any more questions or remarks, feel free to open a new issue ;)
