### ISSUE TITLE
Search page question.  Is this data  (from my spreadsheet) publicly accessible to anyone who has this chrome plugin?

### ISSUE THREAD

**Issue by vally78** [bgotink/IngressIdentity#44]
My concern is that other players may start digging for information and then find my spreadsheet in the process of using the search page.  When i do a search for one of my players i saw the names of the sheets that they were listed on, such as shonin (for the anomaly icon), and when i clicked on it, it pulled up my ACTUAL spreadsheet.  It makes me worry about others being able to do the same.

**Comment by bgotink** [comment]
You control who can access the spreadsheets, using the "share" button in Google Drive. I'd make it private and only share it with specific players.

There's no listing of spreadsheets anywhere. The extension only has access to the sheets you've added to it. Anyone else running the extension won't magically see your spreadsheets :wink: And even if there was such a listing (there isn't), those other players would still need access to the Google Drive spreadsheet before they could read your data!

The search page searches _in the spreadsheets you've added_. That's how it's able to show a list of all the spreadsheets listing a player.
Try finding me on the search page, it won't find me (unless you've added me of course) even though I'm listed in about ten spreadsheets I use.

**Comment by bgotink** [comment]
I'm going to assume the question was answered adequately.
Feel free to re-open if that's not the case!
