### ISSUE TITLE
Community exporter - re-export

### ISSUE THREAD

**Issue by thannemann** [bgotink/IngressIdentity#47]
If I have a community I have already exported and try to re-export the data (update the old data) it seems to not do anything.  even on communities with 25 people it doesnt seem to work.  Is this supported or broken?

**Comment by bgotink** [comment]
It should work, but apparently the last release introduced a bug in the export. The bug occurs when trying to compare known members known in the source files with the members of the community, so the export only works when exporting a new community.

I've got a fix, and I'll upload a new version in the next couple of hours.
