### ISSUE TITLE
[enhancement] button on G+ pages 

### ISSUE THREAD

**Issue by thannemann** [bgotink/IngressIdentity#48]
add a button to personal G+ pages like communities to pull the name and UID to inseert into the sheet

**Comment by thannemann** [comment]
Thank You for the quick attempt, however it does not work.  (see attached) it opens the new window, but does not any a table or any information from the G+ page.

![ingressidentityc1](https://cloud.githubusercontent.com/assets/3686421/9619903/a94fd4f4-50e2-11e5-856a-365dbfad459d.PNG)

**Comment by bgotink** [comment]
Strange, it worked fine on my personal computer. I'll test on my work pc tomorrow.

**Comment by bgotink** [comment]
I've investigated the issue, and it seems that the button only works for players that are already in a spreadsheet. Can you confirm this for me? (i.e. check whether the button works for an agent you know and that it doesn't for an agent you don't know)

**Comment by thannemann** [comment]
I can confirm your findings.

**Comment by bgotink** [comment]
Okay, I've fixed the problem, an updated version of the plugin should be public within the hour.
