### ISSUE TITLE
Updating anomalies

### ISSUE THREAD

**Issue by thannemann** [bgotink/IngressIdentity#50]
What needs to be done to the code to update past and future events? can you tell us where the dependances need to be changed so we could keep the project updated?

**Comment by BramV** [comment]
I have added them in this [commit](https://github.com/bgotink/IngressIdentity/commit/21b2d723a5bd48c6bd7af4d9ac48b7149ac1368e). @bgotink will release a new version soon.
If in the future we forget to add a new one you can make a pull request based on this commit.

**Comment by bgotink** [comment]
Hi @thannemann,

I've uploaded a new version to the Chrome WebStore. It can take up to 60 minutes before it's published.
The images for Obsidian and Aegis Nova have been added.

I've opened #51 about adding info on how to add anomaly images etc.
